# -*- coding: utf-8 -*-
"""App_spam.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XeAg_VxXdKgsmobMZnPTKYKnc6-YPsEI
"""

import streamlit as st
import joblib
import numpy as np

# Configuración de la página
st.set_page_config(page_title="Detector de Spam en Comentarios", page_icon="🛡️")
st.title("🛡️ Detector de Spam en Comentarios de YouTube")
st.write("Escribe un comentario y la IA dirá si es **spam** o **legítimo**.")

# 1. Cargar el modelo guardado
@st.cache_resource
def load_my_model():
    return joblib.load('modelo_spam.pkl')

model = load_my_model()

# 2. Cuadro de texto para introducir el comentario
comentario = st.text_area(
    "✏️ Escribe aquí el comentario:",
    placeholder="Ejemplo: Check out my channel for free music!",
    height=120
)

# 3. Botón para analizar
if st.button("🔍 Analizar comentario"):
    if comentario.strip() == "":
        st.warning("Por favor, escribe un comentario antes de analizar.")
    else:
        # Predicción
        proba = model.predict_proba([comentario])[0]
        pred = model.predict([comentario])[0]
        confianza = np.max(proba)

        # Probabilidad de spam (clase 1)
        prob_spam = proba[1]
        prob_legit = proba[0]

        # 4. Mostrar resultado con umbral de seguridad
        st.subheader("Resultado:")

        if confianza < 0.70:
            st.warning(f"⚠️ Confianza baja ({confianza:.1%}). El modelo no está seguro. Revisa manualmente.")
        elif pred == 1:
            st.error(f"🚨 **SPAM detectado** — Confianza: {confianza:.1%}")
        else:
            st.success(f"✅ **Comentario legítimo** — Confianza: {confianza:.1%}")

        # 5. Gráfica de probabilidades
        st.write("**Distribución de probabilidades:**")
        st.bar_chart({
            "Legítimo (0)": prob_legit,
            "Spam (1)": prob_spam
        })

        # 6. Explicación del umbral
        st.info(
            "🔒 **Nota sobre seguridad:** Si la confianza es menor del 70%, "
            "se recomienda revisión humana. Para aplicaciones críticas puedes "
            "subir este umbral al 90% o más."
        )

# --- Sección de ejemplos para probar ---
st.divider()
st.subheader("💡 Ejemplos para probar:")

col1, col2 = st.columns(2)
with col1:
    st.markdown("**Posible SPAM:**")
    st.code("Subscribe to my channel and get free music!")
    st.code("Check out my new video, click the link in bio!")
    st.code("hi guys please download my app for free followers")

with col2:
    st.markdown("**Posible legítimo:**")
    st.code("I love this song so much, brings back memories!")
    st.code("This video has 2 billion views, incredible.")
    st.code("Best song of 2012 without a doubt.")